str = 'Python Programming Is An Interpetered Language and Python is the easy understandable code '
print(str.capitalize())
print(str.casefold())
print(str.center(60))
print(str.count('Python'))
print(str.encode())
print(str.endswith("."))
print(str.expandtabs(4))
print(str.find('is'))
print(str.format())
print(str.index('an'))
print(str.isalnum())
print(str.isascii())
print(str.isdecimal())
print(str.isdigit())
print(str.isidentifier())
print(str.islower())
print(str.isnumeric())
print(str.replace('Python Programming','C Programming'))
print(str.split())
print(str.rsplit())
print(str.strip())